directories:
  scratch: "/path/to/scratch/folder/"
  src: "/path/to/src/folder/"
  hpc-control: "/path/to/hpc-control/folder/"

use_units: True

simulate_conductance: True

simulate_magnetization_spectrum: False

simulate_spectrum: True

simulate_density: False