wire_width:
  - 7
  # - 10

wire_length:
  # - 56
  - 80

barrier_length:
  - 1

ratio:
  - 0.5

M:
  - 1
  # - 0.05
  # - 0.1

added_sinusoid:
  - True

effective_mass:
  - 1

alpha_R:
  - 0.32
  # - 0.4
  # - 0.8

muSc:
  - 0.22
  # - 0
  # - 0.1
  # - 0.2

mu:
  - 0.3
  # - 0
  # - 0.01
  # - 0.1
  # - 0.2

delta:
  - 0.1

barrier_height:
  - 2

b_max:
  - 1

hopping_distance:
  - 1

bohr_magneton:
  - 1

gfactor:
  - 1

period:
  - 16