wire_width:
  - 7

wire_length:
  - 80

barrier_length:
  - 1

stagger_ratio:
  - 0.5

period:
  - 16

M:
  - 1

hopping_distance:
  - 1

added_sinusoid:
  - True

b_max:
  - 1

bohr_magneton:
  - 1

alpha_R:
  - 0.32

delta:
  - 0.1

gfactor:
  - 1

effective_mass:
  - 1

muSc:
  - 0.22

mu:
  - 0.3

barrier_height:
  - 2
