wire_width: 
  - 7

wire_length:
  - 80

barrier_length:
  - 1

ratio: 
  - 0.5

M:
  - 1

added_sinusoid:
  - True

effective_mass:
  - 0.019

alpha_R:
  - 0.32

muSc:
  - 0

mu:
  - 18.0E-3

delta:
  - 180.0E-6

barrier_height:
  - 0.02

b_max:
  - 2.5

hopping_distance:
  - 200

bohr_magneton:
  - 58.0E-6

gfactor:
  - 10

period:
  - 16
  - 128
  - 1024
  - 8192
