wire_width: # [sites]
  - 7

wire_length: # [sites]
  - 80

barrier_length: # [sites]
  - 1

stagger_ratio: # []
  - 0.5

period: # [Å]
  - 16
  - 128
  - 1024
  - 8192

M: # [T]
  - 1

hopping_distance: # [Å]
  - 200

added_sinusoid: # []
  - True

b_max: # [T]
  - 2.5

bohr_magneton: # [eV/T]
  - 58.0E-6

alpha_R: # [eV Å]
  - 0.32

delta: # [eV]
  - 180.0E-6

gfactor: # []
  - 10

effective_mass: # [m_e]
  - 0.019

muSc: # [eV]
  - 0

mu: # [eV]
  - 18.0E-3

barrier_height: # [eV]
  - 0.02
